#!/usr/bin/env bun

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { Glob } from "bun";

interface PackageJson {
	name?: string;
	version?: string;
	private?: boolean;
	homepage?: string;
	workspaces?: {
		catalog?: Record<string, string>;
	};
}

export interface SyncViolation {
	path: string;
	message: string;
	line?: number;
}
type PublicFetch = (input: string | URL, init?: RequestInit) => Promise<Response>;

const PUBLIC_HOMEPAGE = "https://gajae-code.com";
const GENERATED_DOCS_INDEX = "packages/coding-agent/src/internal-urls/docs-index.generated.ts";
const VERSIONED_MARKETING_RE = /\b(?:New in|Also new in|Gajae Code|Gajae-Code|Feature card for the)\s+(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)\b/gi;
const MARKETING_VERSION_FILES = ["README.md", "docs/**/*.md", "packages/*/README.md"];
const LIVE_FETCH_TIMEOUT_MS = 5_000;

async function pathExists(candidate: string): Promise<boolean> {
	try {
		await fs.access(candidate);
		return true;
	} catch {
		return false;
	}
}

async function readJson<T>(filePath: string): Promise<T> {
	return (await Bun.file(filePath).json()) as T;
}

function toPosix(relativePath: string): string {
	return relativePath.split(path.sep).join("/");
}

function lineForOffset(content: string, offset: number): number {
	let line = 1;
	for (let index = 0; index < offset; index++) {
		if (content.charCodeAt(index) === 10) line++;
	}
	return line;
}

async function packageDirs(repoRoot: string): Promise<string[]> {
	const packagesRoot = path.join(repoRoot, "packages");
	const dirents = await fs.readdir(packagesRoot, { withFileTypes: true });
	return dirents.filter(dirent => dirent.isDirectory()).map(dirent => dirent.name).sort();
}

export async function buildDocsIndexOutput(repoRoot: string): Promise<string> {
	const docsDir = path.join(repoRoot, "docs");
	const glob = new Glob("**/*.md");
	const entries: string[] = [];
	for await (const relativePath of glob.scan(docsDir)) {
		entries.push(toPosix(relativePath));
	}
	entries.sort();

	const docsWithContent = await Promise.all(
		entries.map(async relativePath => ({
			relativePath,
			content: await Bun.file(path.join(docsDir, relativePath)).text(),
		})),
	);

	const mapEntries = docsWithContent
		.map(({ relativePath, content }) => `\t${JSON.stringify(relativePath)}: ${JSON.stringify(content)},`)
		.join("\n");

	return [
		"// Auto-generated by scripts/generate-docs-index.ts - DO NOT EDIT",
		"",
		`export const EMBEDDED_DOC_FILENAMES: readonly string[] = ${JSON.stringify(entries)};`,
		"",
		`export const EMBEDDED_DOCS: Readonly<Record<string, string>> = {`,
		`${mapEntries}`,
		`};`,
		"",
	].join("\n");
}

async function canonicalVersionForRepo(repoRoot: string): Promise<string | undefined> {
	const rootPackage = await readJson<PackageJson>(path.join(repoRoot, "package.json"));
	return rootPackage.workspaces?.catalog?.["@gajae-code/coding-agent"];
}

export async function checkPublicVersionSync(repoRoot = path.join(import.meta.dir, "..")): Promise<SyncViolation[]> {
	const violations: SyncViolation[] = [];
	const rootPackagePath = path.join(repoRoot, "package.json");
	const rootPackage = await readJson<PackageJson>(rootPackagePath);
	const catalog = rootPackage.workspaces?.catalog ?? {};
	const canonicalVersion = catalog["@gajae-code/coding-agent"];

	if (!canonicalVersion) {
		violations.push({ path: "package.json", message: "Missing canonical @gajae-code/coding-agent catalog version." });
		return violations;
	}

	const packageByName = new Map<string, { relativePath: string; data: PackageJson }>();
	for (const dir of await packageDirs(repoRoot)) {
		const relativePath = `packages/${dir}/package.json`;
		const packagePath = path.join(repoRoot, relativePath);
		if (!(await pathExists(packagePath))) continue;
		const pkg = await readJson<PackageJson>(packagePath);
		if (!pkg.name || pkg.private) continue;
		packageByName.set(pkg.name, { relativePath, data: pkg });

		if (pkg.version !== canonicalVersion) {
			violations.push({
				path: relativePath,
				message: `${pkg.name} version ${pkg.version ?? "<missing>"} does not match canonical ${canonicalVersion}.`,
			});
		}

		if (pkg.homepage !== PUBLIC_HOMEPAGE) {
			violations.push({
				path: relativePath,
				message: `${pkg.name} homepage ${pkg.homepage ?? "<missing>"} does not match ${PUBLIC_HOMEPAGE}.`,
			});
		}
	}

	for (const [name, pkg] of packageByName) {
		const catalogVersion = catalog[name];
		if (catalogVersion === undefined) continue;
		if (catalogVersion !== canonicalVersion) {
			violations.push({
				path: "package.json",
				message: `Workspace catalog ${name} version ${catalogVersion} does not match canonical ${canonicalVersion}.`,
			});
		}
		if (catalogVersion !== pkg.data.version) {
			violations.push({
				path: "package.json",
				message: `Workspace catalog ${name} version ${catalogVersion} does not match ${pkg.relativePath} version ${pkg.data.version}.`,
			});
		}
	}

	for (const pattern of MARKETING_VERSION_FILES) {
		const glob = new Glob(pattern);
		for await (const relativePath of glob.scan(repoRoot)) {
			const normalizedPath = toPosix(relativePath);
			const content = await Bun.file(path.join(repoRoot, normalizedPath)).text();
			for (const match of content.matchAll(VERSIONED_MARKETING_RE)) {
				const version = match[1];
				if (version === canonicalVersion) continue;
				violations.push({
					path: normalizedPath,
					line: lineForOffset(content, match.index ?? 0),
					message: `Visible marketing version ${version} does not match canonical ${canonicalVersion}. Use the current version or remove the stale release-number claim.`,
				});
			}
		}
	}

	const generatedDocsPath = path.join(repoRoot, GENERATED_DOCS_INDEX);
	if (await pathExists(path.join(repoRoot, "docs"))) {
		if (!(await pathExists(generatedDocsPath))) {
			violations.push({ path: GENERATED_DOCS_INDEX, message: "Generated docs index is missing." });
		} else {
			const actual = await Bun.file(generatedDocsPath).text();
			const expected = await buildDocsIndexOutput(repoRoot);
			if (actual !== expected) {
				violations.push({
					path: GENERATED_DOCS_INDEX,
					message: "Generated docs index is stale. Run bun run generate-docs-index.",
				});
			}
		}
	}

	return violations;
}

export async function checkLivePublicVersionSync(repoRoot = path.join(import.meta.dir, ".."), fetchImpl: PublicFetch = fetch, timeoutMs = LIVE_FETCH_TIMEOUT_MS): Promise<SyncViolation[]> {
	const violations: SyncViolation[] = [];
	const canonicalVersion = await canonicalVersionForRepo(repoRoot);

	if (!canonicalVersion) {
		violations.push({ path: "package.json", message: "Missing canonical @gajae-code/coding-agent catalog version." });
		return violations;
	}

	let response: Response;
	try {
		response = await fetchImpl(PUBLIC_HOMEPAGE, {
			headers: { "User-Agent": "gajae-code-public-version-sync/1.0" },
			signal: AbortSignal.timeout(timeoutMs),
		});
	} catch (error) {
		const message = error instanceof Error ? error.message : String(error);
		violations.push({ path: PUBLIC_HOMEPAGE, message: `Failed to fetch public homepage: ${message}` });
		return violations;
	}

	if (!response.ok) {
		violations.push({ path: PUBLIC_HOMEPAGE, message: `Public homepage returned HTTP ${response.status}.` });
		return violations;
	}

	const homepage = await response.text();
	const visibleVersion = homepage.match(/\bv(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?)\b/i)?.[1];
	if (!visibleVersion) {
		violations.push({ path: PUBLIC_HOMEPAGE, message: "Public homepage does not expose a visible vX.Y.Z[-fork.N] version marker." });
	} else if (visibleVersion !== canonicalVersion) {
		violations.push({
			path: PUBLIC_HOMEPAGE,
			message: `Public homepage version ${visibleVersion} does not match canonical ${canonicalVersion}. Redeploy or update the public site metadata.`,
		});
	}

	return violations;
}
if (import.meta.main) {
	const live = process.argv.includes("--live");
	const violations = [
		...(await checkPublicVersionSync()),
		...(live ? await checkLivePublicVersionSync() : []),
	];
	if (violations.length === 0) {
		console.log("Public docs/site/version surfaces are in sync.");
		process.exit(0);
	}

	console.error("Public docs/site/version sync check failed:");
	for (const violation of violations) {
		const location = violation.line === undefined ? violation.path : `${violation.path}:${violation.line}`;
		console.error(`- ${location}: ${violation.message}`);
	}
	process.exit(1);
}
